<a href="https://colab.research.google.com/github/arunmozhidevan/MDS271-Machine-Learning/blob/main/Lab_1B_Introduction_to_Machine_Learning_Libraries_Part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 1B - Introduction to Machine Learning Libraries: Part 2
<hr/>

Submitted by <br>
Name: **Arun Mozhi Devan** <br>
Register Number: **21122009** <br>
Class: **MSCDS 2** <br> 
<hr/>


In [1]:
!pip install sklearn

In [23]:
import warnings
warnings.filterwarnings("ignore")

# PART 1 - EXPLORATION

# a. train_test_split from sklearn.model_selection

In [2]:
from sklearn.datasets import load_iris, load_boston
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyClassifier, DummyRegressor
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, recall_score, roc_curve

In [3]:
def box(data, model):
  X = data.data
  y = data.target
  X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=4, test_size=0.2)
  dc = model
  dc.fit(X_train, y_train)
  y_pred = dc.predict(X_test)
  return y_pred, y_test

# b. make_classification and load_iris from sklearn.datasets

In [4]:
iris_data = load_iris()
make_classification = DummyClassifier()

# c. make_regression and load_boston from sklearn.datasets

In [24]:
boston = load_boston()

In [6]:
make_regression = DummyRegressor()

# d. DummyClassifier and DummyRegressor from sklearn.dummy

In [7]:
pred, test = box(iris_data, make_classification)

In [8]:
_pred, _test = box(boston, make_regression)

# e. accuracy_score, classification_report, and confusion_matrix from sklearn.metrics

In [9]:
print(f'Accuracy score : {accuracy_score(pred, test)}\n')
print(f'Confusion matrix : \n{confusion_matrix(pred, test)}\n')
print(f'Classification report: {classification_report(pred, test)}\n')

Accuracy score : 0.16666666666666666

Confusion matrix : 
[[ 0  0  0]
 [16  5  9]
 [ 0  0  0]]

Classification report:               precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.17      0.29        30
           2       0.00      0.00      0.00         0

    accuracy                           0.17        30
   macro avg       0.33      0.06      0.10        30
weighted avg       1.00      0.17      0.29        30




/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# PART 2 - Questions

<hr/>

# What are the different parameters of the above functions/methods that are part of the above SKLearn modules?

load_iris, load_boston, train_test_split, DummyClassifier, DummyRegressor, accuracy_score, classification_report and confusion_matrix

<hr/>

# What is the effect, when you modify certain parameters that are present in the same?

for example if we take train_test_split(X, y, random_state=4, test_size=0.2) test_size 0.2 constitutes 20% percent of the data as test data changing test_size takes difference percentage of test data

as we have given 0.2 as test size test set will have 20% of the data 

In [10]:
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, random_state=4, test_size=0.2)
len(X_test) / len(iris_data.data), len(y_test) / len(iris_data.data)

(0.2, 0.2)

as we have given 0.4 as test size test set will have 40% of the data 

In [11]:
  X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, random_state=4, test_size=0.4)
  len(X_test) / len(iris_data.data), len(y_test) / len(iris_data.data) 

(0.4, 0.4)


<hr/>

# How to get different train and test datasets?<br>

by changing the values of test_size in train_test_split

80% train data and 20% test data

In [12]:
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, random_state=4, test_size=0.2)
len(X_train) / len(iris_data.data), len(y_test) / len(iris_data.data) 

(0.8, 0.2)

60% train data and 40% test data

In [13]:
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, random_state=4, test_size=0.4)
len(X_train) / len(iris_data.data), len(y_test) / len(iris_data.data) 

(0.6, 0.4)


<hr/>

# Identify which are features and which are targets in Part 1b, and Part 1c (make_classification and make_regression would depend on your inputs on the function call)<br>

In both make_classification and make_regression, the load_iris.data and load_boston.data will be the features and load_iris.target and load_boston.target is the target

In [14]:
import pandas as pd

below will be our feature and data

In [15]:
pd.DataFrame(data=load_iris().data, columns=load_iris()['feature_names'])

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

this will be our target values

In [16]:
pd.DataFrame(data=load_iris().target, columns=['target'])['target'].map({0:'setosa',1:'versicolor',2:'virginica'})

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: target, Length: 150, dtype: object

In [17]:
pd.DataFrame(data=load_boston().data, columns=load_boston()['feature_names']) # will our feature and data

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   7.88

[506 rows x 13 columns]

<hr/>

# Identify what the things mentioned in Part 1d stands for. <br>

dummy.DummyClassifier --> makes predictions that ignore the input features.

dummy.DummyRegressor --> makes predictions using simple rules.


<hr/>

# Making use of Part 1d, explore the various options available under Part 1e.

some of the other avilable options are metrics.recall_score, metrics.roc_curve

In [18]:
pred, test = box(iris_data, DummyClassifier())
from sklearn.metrics import balanced_accuracy_score, completeness_score, max_error

The balanced accuracy in binary and multiclass classification problems to deal with imbalanced datasets. It is defined as the average of recall obtained on each class.

In [19]:
print(f'balanced_accuracy_score : {balanced_accuracy_score(pred, test)}\n')

balanced_accuracy_score : 0.16666666666666666



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")


A clustering result satisfies completeness if all the data points that are members of a given class are elements of the same cluster.

In [20]:
print(f'completeness_score : {completeness_score(pred, test)}\n')

completeness_score : 0.0



The max_error metric calculates the maximum residual error.

In [21]:
print(f'max_error : {max_error(pred, test)}\n')

max_error : 1

